### ISSUE TITLE
Support for Upsert on PG?

### ISSUE THREAD

**Issue by ehmo** [Masterminds/squirrel#90] opened 2017-04-24 21:52 UTC
Hi guys,

Great library. Was using it for the past day or so and was wondering if there is a support for the Postgresql's Upsert [ON CONFLICT](https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT) statements.

**Comment by RoarkeRandall** [comment] 2017-10-02 20:42
should be merged w/ https://github.com/Masterminds/squirrel/issues/83

**Comment by lann** [comment] 2017-11-30 16:24
Dupe of #83

**Closed by lann** 2017-11-30 16:24 UTC
